name: Refresh product versions

on:
  schedule:
    - cron: '19 3 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Run updater
        run: ./update
      - uses: actions/upload-artifact@v4
        with:
          name: error.html
          path: ./error.html
          retention-days: 1
          overwrite: true

      - name: Commit changes, if any
        uses: EndBug/add-and-commit@v9
        with:
          add: 'data'
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'Automatic package update'
